import { clientsClaim } from 'workbox-core';
import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { NetworkFirst, CacheFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';

// Give the service worker control immediately
clientsClaim();
self.skipWaiting();

// Clean up old caches
cleanupOutdatedCaches();

// Precache all assets generated by the build process
// This is where vite-plugin-pwa injects the manifest
precacheAndRoute(self.__WB_MANIFEST);

// Cache OpenFoodFacts API requests
const apiStrategy = new NetworkFirst({
  cacheName: 'api-cache',
  networkTimeoutSeconds: 5,
  plugins: [
    new ExpirationPlugin({
      maxEntries: 50,
      maxAgeSeconds: 24 * 60 * 60, // 24 hours
    }),
  ],
});

registerRoute(
  ({ url }) => url.hostname === 'world.openfoodfacts.org',
  async (options) => {
    try {
      return await apiStrategy.handle(options);
    } catch (error) {
      const cache = await caches.open('api-cache');
      const cachedResponse = await cache.match(options.request);
      if (cachedResponse) {
        return cachedResponse;
      }

      return new Response(
        JSON.stringify({
          status: 0,
          error: 'offline',
          message: 'You are offline. Cached data may be available.',
        }),
        {
          headers: { 'Content-Type': 'application/json' },
          status: 503,
        }
      );
    }
  }
);

// Cache images
registerRoute(
  ({ request }) => request.destination === 'image',
  new CacheFirst({
    cacheName: 'images',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 60,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
      }),
    ],
  })
);

// Offline fallback for navigation
// This handles the SPA offline experience
const handler = async (options) => {
  try {
    // Try network first with a timeout
    return await new NetworkFirst({
      cacheName: 'pages',
      networkTimeoutSeconds: 3,
    }).handle(options);
  } catch (error) {
    return caches.match('/index.html');
  }
};

registerRoute(new NavigationRoute(handler));